export const images = {
    checked: require('./images/checked.png'),
    unChecked: require('./images/unchecked.png'),
    footerbg: require('./images/footerbg.png'),
    chatActive: require('./images/chat-active.png'),
    chat: require('./images/chat.png'),
    people: require('./images/people.png'),
    peopleActive: require('./images/people-active.png'),
    discover: require('./images/discover.png'),
    discoverActive: require('./images/discover-active.png'),
    camera: require('./images/camera.png'),
    videoCall: require('./images/video-call.png'),
    call: require("./images/call.png"),
    conversationSettings: require('./images/conversation-settings.png'),
    notifications: require('./images/notifications.png'),
    deleteConversation: require('./images/delete-conversation.png'),
    avatar: require("./images/avatar.png"),
    photo: require('./images/photo.png'),
    newMessage: require("./images/new-message.png"),
    search: require('./images/search.png'),
    yourStory: require( './images/your-story.png' ),
    request: require( './images/requests.png' ),
    addContact: require( "./images/add-contact.png" ),
    wave: require( "./images/wave.png" ),
    group: require('./images/g.jpg'),
    online: require('./images/online.png')
}